### ISSUE TITLE
Reconsider or refine dependabot updates

### ISSUE THREAD

**Issue by AdrianDAlessandro** [ImperialCollegeLondon/imperial_coldfront_plugin#29]
There are currently 5 PRs attempting to update the requirements that are failing because `coldfront` has pinned requirements.

We should prevent Dependabot from trying to update secondary dependancies like this. This is a general pain point with using Dependabot with pip-tools, so it'd be nice to work out how to configure that.

**Comment by AdrianDAlessandro** [comment]
I am considering using Renovate instead of Dependabot. They have a [pip-compile-specific dependency manager](https://docs.renovatebot.com/modules/manager/pip-compile/)

Thoughts @cc-a

**Comment by cc-a** [comment]
Worth a go I think.

**Comment by AdrianDAlessandro** [comment]
Kind of fell at the first hurdle with this. I tried to configure the [Renovate GitHub App](https://github.com/apps/renovate) for this repo and I wasn't able to get it to access the repo. I had to request access, and I thought that since I'm an admin for the repo, I would be able to grant the access, but I was not. Did you see anything @cc-a ?
